-- ============================================================
--  01_TABLES.SQL
--  Tablo tanımları, kısıtlamalar, sequence ve index
--  Çalıştırma sırası: Bu dosya en önce çalıştırılmalıdır.
-- ============================================================

-- ============================================================
-- TABLE: MST_MUSTERI
-- ============================================================

CREATE TABLE MST_MUSTERI (
    MUSTERI_ID        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    AD                VARCHAR2(100) NOT NULL,
    SOYAD             VARCHAR2(100),
    MUSTERI_TIPI      NUMBER(1)     NOT NULL, -- 1: Bireysel, 2: Tüzel
    KIMLIK_NO         VARCHAR2(11)  NOT NULL,
    EMAIL             VARCHAR2(150) NOT NULL,
    TELEFON           VARCHAR2(20)  NOT NULL,
    AKTIF_MI          NUMBER(1)     DEFAULT 1   NOT NULL,
    OLUSTURMA_TARIHI  DATE          DEFAULT SYSDATE NOT NULL,
    GUNCELLEME_TARIHI DATE,
    CONSTRAINT UQ_MUSTERI_EMAIL UNIQUE (EMAIL),
    CONSTRAINT UQ_MUSTERI_KIMLIK_NO UNIQUE (KIMLIK_NO),
    CONSTRAINT CHK_MUSTERI_AKTIF CHECK (AKTIF_MI IN (1, 2)), -- 1: Aktif, 2: Pasif
    CONSTRAINT CHK_MUSTERI_SOYAD CHECK ((MUSTERI_TIPI = 1 AND SOYAD IS NOT NULL) OR (MUSTERI_TIPI = 2)),
    CONSTRAINT CHK_MUSTERI_EMAIL_FORMAT CHECK (REGEXP_LIKE(EMAIL, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')),
    CONSTRAINT CHK_MUSTERI_TELEFON CHECK (REGEXP_LIKE(TRIM(TELEFON), '^[0-9]{10,15}$'))
);

-- ============================================================
-- TABLE: MST_MUSTERIADRES
-- ============================================================

CREATE TABLE MST_MUSTERIADRES (
    ADRES_ID          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MUSTERI_ID        NUMBER        NOT NULL,
    ADRES_BASLIK      VARCHAR2(50),
    ULKE              VARCHAR2(100) NOT NULL,
    SEHIR             VARCHAR2(100) NOT NULL,
    ILCE              VARCHAR2(100),
    POSTA_KODU        VARCHAR2(20),
    ACIK_ADRES        VARCHAR2(500) NOT NULL,
    OLUSTURMA_TARIHI  DATE DEFAULT SYSDATE NOT NULL,
    GUNCELLEME_TARIHI DATE,
    CONSTRAINT FK_MUSTERIADRES_MUSTERI
        FOREIGN KEY (MUSTERI_ID)
        REFERENCES MST_MUSTERI (MUSTERI_ID)
        ON DELETE CASCADE
);

CREATE INDEX IX_MUSTERIADRES_MUSTERI_ID
    ON MST_MUSTERIADRES (MUSTERI_ID);

-- ============================================================
-- TABLE: MVD_HESAP
-- ============================================================

CREATE TABLE MVD_HESAP (
    HESAP_NO     VARCHAR2(20)  PRIMARY KEY,
    MUSTERI_ID   NUMBER        NOT NULL,
    IBAN         VARCHAR2(34),
    HESAP_TURU   VARCHAR2(30),
    DOVIZ_CINSI  VARCHAR2(3)   NOT NULL,
    BAKIYE       NUMBER(18, 4) DEFAULT 0 NOT NULL,
    DURUM        NUMBER(1)     DEFAULT 1 NOT NULL, -- 1: Aktif, 2: Pasif, 3: Kapalı
    CONSTRAINT FK_HESAP_MUSTERI
        FOREIGN KEY (MUSTERI_ID)
        REFERENCES MST_MUSTERI (MUSTERI_ID),
    CONSTRAINT CHK_HESAP_DURUM
        CHECK (DURUM IN (1, 2, 3))
);

CREATE INDEX IX_HESAP_MUSTERI_ID
    ON MVD_HESAP (MUSTERI_ID);

-- ============================================================
-- TABLE: MVD_HESAPHAREKET
-- ============================================================

CREATE TABLE MVD_HESAPHAREKET (
    ISLEM_ID     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    HESAP_NO     VARCHAR2(20)  NOT NULL,
    ISLEM_YONU   CHAR(1)       NOT NULL,
    ISLEM_TUTARI NUMBER(18, 4) NOT NULL,
    DOVIZ_CINSI  VARCHAR2(3)   NOT NULL,
    YENI_BAKIYE  NUMBER(18, 4) NOT NULL,
    ISLEM_TARIHI TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    ACIKLAMA     VARCHAR2(200),
    ISLEM_KODU   VARCHAR2(20),
    REFERANS_NO  VARCHAR2(50),
    CONSTRAINT FK_HAREKET_HESAP
        FOREIGN KEY (HESAP_NO)
        REFERENCES MVD_HESAP (HESAP_NO),
    CONSTRAINT CHK_HAREKET_ISLEM_YONU
        CHECK (ISLEM_YONU IN ('B', 'C'))
);

CREATE INDEX IX_HAREKET_HESAP_NO
    ON MVD_HESAPHAREKET (HESAP_NO);

CREATE INDEX IX_HAREKET_HESAP_TARIH
    ON MVD_HESAPHAREKET (HESAP_NO, ISLEM_TARIHI DESC);

-- ============================================================
-- TABLE: MUH_FIS
-- Muhasebe fisi baslik bilgisi. MUH_* on eki muhasebe konu alanini
-- gosterir (MST_: ana veri, MVD_: hareket verisi).
-- ============================================================

CREATE TABLE MUH_FIS (
    FIS_ID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ACIKLAMA       VARCHAR2(200),
    MUHASEBETARIHI DATE      DEFAULT TRUNC(SYSDATE) NOT NULL, -- fisin muhasebelestigi gun
    ISLEM_ZAMANI   TIMESTAMP DEFAULT SYSTIMESTAMP  NOT NULL   -- fisin kaydedildigi an (saat dahil)
);

CREATE INDEX IX_MUH_FIS_MUHASEBETARIHI
    ON MUH_FIS (MUHASEBETARIHI DESC);

-- ============================================================
-- TABLE: MUH_FIS_HAREKET
-- Fisin borc/alacak satirlari. Bir satir ya borc ya alacak olur;
-- ikisi ayni anda dolu olamaz (cift tarafli kayit kurali).
-- ============================================================

CREATE TABLE MUH_FIS_HAREKET (
    FIS_HAREKET_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FIS_ID         NUMBER        NOT NULL,
    HESAP_NO       VARCHAR2(20),
    BORC_TUTARI    NUMBER(18, 4) DEFAULT 0 NOT NULL,
    ALACAK_TUTARI  NUMBER(18, 4) DEFAULT 0 NOT NULL,
    SKONT          VARCHAR2(50),                        -- islem/hesap kodu, orn. '002-Bankacilik Islemleri'
    DOVIZ_KURU     NUMBER(18, 6) DEFAULT 1 NOT NULL,    -- TL karsiligi icin kur (TL satirlarda 1)
    CONSTRAINT FK_FIS_HAREKET_FIS
        FOREIGN KEY (FIS_ID)
        REFERENCES MUH_FIS (FIS_ID)
        ON DELETE CASCADE,
    CONSTRAINT FK_FIS_HAREKET_HESAP
        FOREIGN KEY (HESAP_NO)
        REFERENCES MVD_HESAP (HESAP_NO),
    CONSTRAINT CHK_FIS_HAREKET_TUTAR
        CHECK (BORC_TUTARI >= 0 AND ALACAK_TUTARI >= 0
               AND (BORC_TUTARI = 0 OR ALACAK_TUTARI = 0)),
    CONSTRAINT CHK_FIS_HAREKET_KUR
        CHECK (DOVIZ_KURU > 0)
);

CREATE INDEX IX_MUH_FIS_HAREKET_FIS_ID
    ON MUH_FIS_HAREKET (FIS_ID);

CREATE INDEX IX_MUH_FIS_HAREKET_HESAP_NO
    ON MUH_FIS_HAREKET (HESAP_NO);

-- ============================================================
-- TABLE: MVD_ADMIN
-- ============================================================

CREATE TABLE MVD_ADMIN (
    ADMIN_ID       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    KULLANICI_ADI  VARCHAR2(50)  NOT NULL,
    SIFRE          VARCHAR2(255) NOT NULL,
    CONSTRAINT UQ_ADMIN_KULLANICI_ADI UNIQUE (KULLANICI_ADI)
);

-- Varsayilan admin kaydi
INSERT INTO MVD_ADMIN (KULLANICI_ADI, SIFRE)
SELECT 'ADMIN', 'admin123'
    FROM DUAL
 WHERE NOT EXISTS (
             SELECT 1
                 FROM MVD_ADMIN
                WHERE UPPER(KULLANICI_ADI) = 'ADMIN'
 );

COMMIT;

-- ============================================================
-- HISTORY OBJECTS
-- ============================================================

-- ============================================================
-- HISTORY OBJECTS (Gereksiz Sütunlardan Arındırılmış Hal)
-- ============================================================

CREATE SEQUENCE SEQ_ISLEM_H_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE MST_MUSTERI_H (
    H_ID                NUMBER PRIMARY KEY,
    H_ISLEM_TIPI        VARCHAR2(1)    NOT NULL,
    H_ISLEM_TARIHI      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    H_ISLEM_YAPAN       VARCHAR2(128)  NOT NULL,
    MUSTERI_ID          NUMBER,
    AD                  VARCHAR2(100),
    SOYAD               VARCHAR2(100),
    MUSTERI_TIPI        NUMBER(1),
    KIMLIK_NO           VARCHAR2(11),
    EMAIL               VARCHAR2(150),
    TELEFON             VARCHAR2(20),
    AKTIF_MI            NUMBER(1),
    CONSTRAINT CHK_MST_MUSTERI_H_ISLEM
        CHECK (H_ISLEM_TIPI IN ('I', 'U', 'D'))
);

CREATE TABLE MST_MUSTERIADRES_H (
    H_ID                NUMBER PRIMARY KEY,
    H_ISLEM_TIPI        VARCHAR2(1)    NOT NULL,
    H_ISLEM_TARIHI      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    H_ISLEM_YAPAN       VARCHAR2(128)  NOT NULL,
    ADRES_ID            NUMBER,
    MUSTERI_ID          NUMBER,
    ADRES_BASLIK        VARCHAR2(50),
    ULKE                VARCHAR2(100),
    SEHIR               VARCHAR2(100),
    ILCE                VARCHAR2(100),
    POSTA_KODU          VARCHAR2(20),
    ACIK_ADRES          VARCHAR2(500),
    CONSTRAINT CHK_MST_MUSTERIADRES_H_ISLEM
        CHECK (H_ISLEM_TIPI IN ('I', 'U', 'D'))
);

CREATE TABLE MVD_HESAP_H (
    H_ID                NUMBER PRIMARY KEY,
    H_ISLEM_TIPI        VARCHAR2(1)    NOT NULL,
    H_ISLEM_TARIHI      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    H_ISLEM_YAPAN       VARCHAR2(128)  NOT NULL,
    HESAP_NO            VARCHAR2(20),
    MUSTERI_ID          NUMBER,
    IBAN                VARCHAR2(34),
    HESAP_TURU          VARCHAR2(30),
    DOVIZ_CINSI         VARCHAR2(3),
    BAKIYE              NUMBER(18, 4),
    DURUM               NUMBER(1),
    CONSTRAINT CHK_MVD_HESAP_H_ISLEM
        CHECK (H_ISLEM_TIPI IN ('I', 'U', 'D'))
);

CREATE TABLE MVD_HESAPHAREKET_H (
    H_ID                NUMBER PRIMARY KEY,
    H_ISLEM_TIPI        VARCHAR2(1)    NOT NULL,
    H_ISLEM_TARIHI      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    H_ISLEM_YAPAN       VARCHAR2(128)  NOT NULL,
    ISLEM_ID            NUMBER,
    HESAP_NO            VARCHAR2(20),
    ISLEM_YONU          CHAR(1),
    ISLEM_TUTARI        NUMBER(18, 4),
    DOVIZ_CINSI         VARCHAR2(3),
    YENI_BAKIYE         NUMBER(18, 4),
    ACIKLAMA            VARCHAR2(200),
    ISLEM_KODU          VARCHAR2(20),
    REFERANS_NO         VARCHAR2(50),
    CONSTRAINT CHK_MVD_HESAPHAREKET_H_ISLEM
        CHECK (H_ISLEM_TIPI IN ('I', 'U', 'D'))
);

CREATE TABLE MUH_FIS_H (
    H_ID                NUMBER PRIMARY KEY,
    H_ISLEM_TIPI        VARCHAR2(1)    NOT NULL,
    H_ISLEM_TARIHI      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    H_ISLEM_YAPAN       VARCHAR2(128)  NOT NULL,
    FIS_ID              NUMBER,
    ACIKLAMA            VARCHAR2(200),
    MUHASEBETARIHI      DATE,
    ISLEM_ZAMANI        TIMESTAMP,
    CONSTRAINT CHK_MUH_FIS_H_ISLEM
        CHECK (H_ISLEM_TIPI IN ('I', 'U', 'D'))
);

CREATE TABLE MUH_FIS_HAREKET_H (
    H_ID                NUMBER PRIMARY KEY,
    H_ISLEM_TIPI        VARCHAR2(1)    NOT NULL,
    H_ISLEM_TARIHI      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    H_ISLEM_YAPAN       VARCHAR2(128)  NOT NULL,
    FIS_HAREKET_ID      NUMBER,
    FIS_ID              NUMBER,
    HESAP_NO            VARCHAR2(20),
    BORC_TUTARI         NUMBER(18, 4),
    ALACAK_TUTARI       NUMBER(18, 4),
    SKONT               VARCHAR2(50),
    DOVIZ_KURU          NUMBER(18, 6),
    CONSTRAINT CHK_MUH_FIS_HAREKET_H_ISLEM
        CHECK (H_ISLEM_TIPI IN ('I', 'U', 'D'))
);

-- ============================================================
-- TABLE: MVD_GUNLUK_ISLEM_HACMI
-- Ayin 1'inden bugune kadar gunluk mutlak islem hacmi
-- ============================================================

CREATE TABLE MVD_GUNLUK_ISLEM_HACMI (
    HACIM_TARIHI          DATE PRIMARY KEY,
    ISLEM_ADEDI           NUMBER       DEFAULT 0 NOT NULL,
    TOPLAM_MUTLAK_TUTAR   NUMBER(18,4) DEFAULT 0 NOT NULL,
    SON_GUNCELLEME_TARIHI TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL
);