-- ============================================================
--  05_CLEANUP_UNUSED_OBJECTS.SQL
--  Mevcut veritabanından gereksiz ve kopya olan eski 
--  yapıları temizleme betiğidir.
-- ============================================================

SET SERVEROUTPUT ON;

BEGIN
    -- 1. MST_MUSTERI_SEQ silinmesi
    -- GENERATED BY DEFAULT AS IDENTITY varken gereksizdir.
    BEGIN
        EXECUTE IMMEDIATE 'DROP SEQUENCE MST_MUSTERI_SEQ';
        DBMS_OUTPUT.PUT_LINE('MST_MUSTERI_SEQ silindi.');
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -2289 THEN -- -2289: Sequence does not exist
                RAISE;
            ELSE
                DBMS_OUTPUT.PUT_LINE('MST_MUSTERI_SEQ zaten yok.');
            END IF;
    END;

    -- 2. SEQ_HESAPHAREKET_ID silinmesi
    -- Tablo identity column kullanacak sekilde guncelleneceginden gereksiz.
    BEGIN
        EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_HESAPHAREKET_ID';
        DBMS_OUTPUT.PUT_LINE('SEQ_HESAPHAREKET_ID silindi.');
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -2289 THEN
                RAISE;
            ELSE
                DBMS_OUTPUT.PUT_LINE('SEQ_HESAPHAREKET_ID zaten yok.');
            END IF;
    END;

    -- 3. sp_mevduat_ekle prosedürünün silinmesi (Gereksiz wrapper)
    BEGIN
        EXECUTE IMMEDIATE 'DROP PROCEDURE sp_mevduat_ekle';
        DBMS_OUTPUT.PUT_LINE('sp_mevduat_ekle silindi.');
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -4043 THEN -- -4043: Object does not exist
                RAISE;
            ELSE
                DBMS_OUTPUT.PUT_LINE('sp_mevduat_ekle zaten yok.');
            END IF;
    END;

    -- 4. sp_mevduat_hareket_ekle prosedürünün silinmesi (Gereksiz wrapper)
    BEGIN
        EXECUTE IMMEDIATE 'DROP PROCEDURE sp_mevduat_hareket_ekle';
        DBMS_OUTPUT.PUT_LINE('sp_mevduat_hareket_ekle silindi.');
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -4043 THEN
                RAISE;
            ELSE
                DBMS_OUTPUT.PUT_LINE('sp_mevduat_hareket_ekle zaten yok.');
            END IF;
    END;

    -- 5. sp_hesap_ekle prosedurunun silinmesi (PKG_HESAP.PRC_HESAP_EKLE ile degistirildi)
    BEGIN
        EXECUTE IMMEDIATE 'DROP PROCEDURE sp_hesap_ekle';
        DBMS_OUTPUT.PUT_LINE('sp_hesap_ekle silindi.');
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -4043 THEN -- -4043: Object does not exist
                RAISE;
            ELSE
                DBMS_OUTPUT.PUT_LINE('sp_hesap_ekle zaten yok.');
            END IF;
    END;

    -- 6. sp_hesap_hareket_ekle prosedurunun silinmesi (PKG_HESAP.PRC_HAREKET_EKLE ile degistirildi)
    BEGIN
        EXECUTE IMMEDIATE 'DROP PROCEDURE sp_hesap_hareket_ekle';
        DBMS_OUTPUT.PUT_LINE('sp_hesap_hareket_ekle silindi.');
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -4043 THEN
                RAISE;
            ELSE
                DBMS_OUTPUT.PUT_LINE('sp_hesap_hareket_ekle zaten yok.');
            END IF;
    END;

    -- NOT: TRG_AUD_* trigger'lari, MST_MUSTERI_H / MST_MUSTERIADRES_H / MVD_HESAP_H /
    -- MVD_HESAPHAREKET_H history tablolari ve SEQ_ISLEM_H_ID sequence'i BURADAN
    -- KASITLI OLARAK CIKARILDI. Bunlar "kullanilmayan eski nesneler" degil,
    -- 01_Tables.sql ve 02_Triggers.sql tarafindan olusturulan ve halen aktif
    -- calisan audit/history mekanizmasinin kendisidir. Bu script'in eski
    -- versiyonu bunlari silmeye calisiyordu; calistirilsaydi yeni kurulan
    -- audit altyapisini tamamen yok ederdi.
END;
/