-- ============================================================
--  ALTER_TABLE.SQL
--  Eski kurulumlarda MVD_HESAPHAREKET.ISLEM_ID identity DEGILSE onu
--  identity kolonuna cevirmek icin kullanilan bakim betigidir.
--  01_Tables.sql zaten ISLEM_ID'yi identity olarak tanimlar; bu yuzden
--  yeni kurulumlarda GEREKSIZDIR. Idempotent olmasi icin, kolon zaten
--  identity ise hicbir sey yapmaz (aksi halde ORA-30673 alinirdi).
--  Nesneler baglanan kullanicinin kendi semasinda islenir.
-- ============================================================

SET SERVEROUTPUT ON;

DECLARE
    v_is_identity USER_TAB_COLUMNS.IDENTITY_COLUMN%TYPE;
BEGIN
    SELECT IDENTITY_COLUMN
      INTO v_is_identity
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME  = 'MVD_HESAPHAREKET'
       AND COLUMN_NAME = 'ISLEM_ID';

    IF v_is_identity = 'YES' THEN
        DBMS_OUTPUT.PUT_LINE('ISLEM_ID zaten identity kolonu. Islem yapilmadi.');
    ELSE
        EXECUTE IMMEDIATE
            'ALTER TABLE MVD_HESAPHAREKET MODIFY ISLEM_ID GENERATED BY DEFAULT AS IDENTITY';
        DBMS_OUTPUT.PUT_LINE('ISLEM_ID identity kolonuna cevrildi.');
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('MVD_HESAPHAREKET.ISLEM_ID bulunamadi.');
END;
/
