-- ============================================================
--  RECREATE_TABLE.SQL
--  SADECE MVD_HESAPHAREKET tablosunu bastan olusturmak icin
--  bakim/onarim betigidir. Tablonun tanimi 01_Tables.sql ile
--  BIREBIR AYNIDIR; normal kurulumda buna GEREK YOKTUR.
--
--  DIKKAT: MVD_HESAPHAREKET icindeki TUM HAREKET VERISI silinir.
--  Nesneler baglanan kullanicinin kendi semasinda islenir.
-- ============================================================

DROP TABLE MVD_HESAPHAREKET CASCADE CONSTRAINTS;

CREATE TABLE MVD_HESAPHAREKET (
    ISLEM_ID     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    HESAP_NO     VARCHAR2(20)  NOT NULL,
    ISLEM_YONU   CHAR(1)       NOT NULL,
    ISLEM_TUTARI NUMBER(18, 4) NOT NULL,
    DOVIZ_CINSI  VARCHAR2(3)   NOT NULL,
    YENI_BAKIYE  NUMBER(18, 4) NOT NULL,
    ISLEM_TARIHI TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    ACIKLAMA     VARCHAR2(200),
    ISLEM_KODU   VARCHAR2(20),
    REFERANS_NO  VARCHAR2(50),
    CONSTRAINT FK_HAREKET_HESAP
        FOREIGN KEY (HESAP_NO)
        REFERENCES MVD_HESAP (HESAP_NO),
    CONSTRAINT CHK_HAREKET_ISLEM_YONU
        CHECK (ISLEM_YONU IN ('B', 'C'))
);

CREATE INDEX IX_HAREKET_HESAP_NO
    ON MVD_HESAPHAREKET (HESAP_NO);

CREATE INDEX IX_HAREKET_HESAP_TARIH
    ON MVD_HESAPHAREKET (HESAP_NO, ISLEM_TARIHI DESC);

-- Tabloya bagli trigger'lar DROP ile birlikte silindigi icin yeniden derlenir
@@02_Triggers.sql
